on:
  push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.9.15

      - name: Install pipenv
        run: pip install pipenv

      - name: Install Core Utilities
        run: make install

      - name: Install Dependencies
        run: make deps

      - name: Install Panther CLI
        run: pipenv run -- pip3 install -e .

      - name: Run CLI Tests
        run: make ci

      - name: Test building a release will work
        run: |
          rm -rf dist
          pipenv run python3 setup.py sdist
          pipenv run pip install dist/*.tar.gz
          pipenv run panther_analysis_tool --version
