name: Release panther_analysis_tool

on:
  push:
    branches:
      - "master"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Clean old release (if any)
      run: rm -rf dist

    - name: Build release package
      run: poetry build

    - name: Test package works
      run: |
        pip install dist/*.tar.gz dist/*.whl
        poetry run panther_analysis_tool --version

    - name: Publish to pypi
      run: poetry publish
      env:
        POETRY_HTTP_BASIC_PYPI_USERNAME: panther
        POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}